### ISSUE TITLE
data

### ISSUE THREAD

**Issue by sunshine795** [dscheepens/Deep-RNN-for-extreme-wind-speed-prediction#1]
Hello, can you provide some data（'../../../../../../mnt/data/scheepensd94dm/'）?

**Comment by dscheepens** [comment]
Hi, best if you download the data yourself from the Copernicus Climate Data Store. I've added the file grib_to_numpy.py which includes the link to the data and transforms from .grib to .npy. Don't forget to change the 'root' to your root (also in main.py).

**Comment by sunshine795** [comment]
Thank you very much. I'll try it on

**Comment by sunshine795** [comment]
Hello, my Windows system cannot install pygrib library, can I consider using NetCDF data format?

**Comment by dscheepens** [comment]
Do you have pip installed and tried: 
pip install pyproj
pip install pygrib
? 
The library should work for windows.

**Comment by sunshine795** [comment]
Hello, I have downloaded the data to the required directory, how should I train it next? For example, what is the order in which files are run?

**Comment by dscheepens** [comment]
Hi, just set up in main.py which parameters you want to use (e.g. loss function, number of layers etc.) and then run: python3 main.py 

Make sure you have all the relevant packages installed

**Comment by dscheepens** [comment]
Please let me know if there are any other issues. The code still needs a bit of curating to be sure.

**Comment by sunshine795** [comment]
Hi,in file "loss_functions.py", "ser_t = ((preds[indices]-targets[indices])**2).mean()"position error is "IndexError: too many indices for tensor of dimension 3".

How to solve it?

**Comment by dscheepens** [comment]
Hi, is your data of dimension (N, 12, 64, 64) where N is the number of samples? 

You can also just use the standard MSE loss if you just want to get the code running. We tested the SERA loss in our paper but you can of course use any loss.
